name = "energy-production"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB_ENERGY"
database_name = "energy"
database_id = "5dfeb585-9598-41c5-a485-52d2831e4ec2"

[[d1_databases]]
binding = "DB_METEO"
database_name = "meteo"
database_id = "17e827ee-3f96-4ce9-b93c-be3cea624448"

[[d1_databases]]
binding = "DB_SEESTRASSE"
database_name = "seestrasse52b"
database_id = "8114362a-d78d-4c17-9f47-9abee82f3e26"
