name = "ekz-dynamic-price-collector"
main = "src/index.js"
compatibility_date = "2026-09-01"

# Täglich um 22:00 UTC
[triggers]
crons = ["0 22 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "energy"
database_id = "5dfeb585-9598-41c5-a485-52d2831e4ec2"

# Tarifnamen (per Swagger/Tarifliste prüfen, ohne Code-Änderung anpassbar)
[vars]
ENERGY_TARIFF = "electricity_dynamic"
GRID_TARIFF = "grid_400D_inclFees"
